package com.example.a1.events;

public enum EventType {
    VOTED_ANSWER, VOTED_QUESTION,
    ANSWER_CREATED, ANSWER_UPDATED, ANSWER_DELETED,
    QUESTION_CREATED, QUESTION_UPDATED, QUESTION_DELETED,
    USER_BANNED, USER_UPDATED
}
